### ISSUE TITLE
Indiana Parsed Corpus of Historical German

### ISSUE THREAD

**Issue by cdsapp** [acoli-repo/germhist#3]
Hi,
Would you like to link to our corpus? It's underdevelopment and at the moment has about 160,000 words of ENHG.  https://ipchg.iu.edu/

**Comment by chiarcos** [comment]
Thanks for the suggestion. Will do (and it will be straight-forward because it's PTB-style), but might take a moment.

BTW: Do you know about the Caitlin Light (2011) ENHG corpus? Original website is down, I have a mirror under https://github.com/acoli-repo/acoli-corpora/tree/master/external/enhgcorpus. This should be pretty close to your schema, but AFAIK, it isn't maintained, but you might incorporate it (with appropriate attribution, etc.) and validate her annotations.
